name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build for mips_24kc
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch upstream git reversion
        id: op_version
        run: echo sha=$(cat .nvchecker/sha) >> $GITHUB_OUTPUT

      - name: Build Package
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: mips_24kc-main
          V: s
          IGNORE_ERRORS: n m y
          NO_DEFAULT_FEEDS: 1
          EXTRA_FEEDS: >-
            src-git-full|base|https://github.com/openwrt/openwrt.git
            src-git|packages|https://github.com/growtopiajaw/packages.git^${{ steps.op_version.outputs.sha }}
          PACKAGES: cloudflared

      - name: Upload Output Folder
        uses: actions/upload-artifact@v4
        with:
          name: cloudflared-mips_24kc
          path: bin/packages/mips_24kc/packages/cloudflared_*.ipk

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.ipk"
